# Generated by Django 5.0.1 on 2024-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adhar_num',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='user/'),
        ),
    ]
