# Generated by Django 5.0.1 on 2024-03-06 20:47

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to=voting.models.user_image_path),
        ),
    ]
