# Generated by Django 5.0.1 on 2024-03-08 11:48

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=voting.models.user_image_path),
        ),
    ]
