# Generated by Django 5.0.1 on 2024-03-11 18:08

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=150, unique=True)),
                ('e_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(default=None, max_length=100)),
                ('sym_name', models.CharField(max_length=24, unique=True)),
                ('sym_img', models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=voting.models.party_image_path)),
            ],
        ),
    ]
