# Generated by Django 5.0.1 on 2024-03-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_election_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(default=None, max_length=100)),
                ('adhar_num', models.CharField(default=None, max_length=12)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.parties')),
            ],
        ),
    ]
