# Generated by Django 5.0.1 on 2024-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
